### ISSUE TITLE
npm run dev启动失败

### ISSUE THREAD

**Issue by wcc1433** [alex8088/EvPlayer#1]
error during start dev server and electron app:
Error: Electron uninstall
    at Object.getElectronPath (D:\WorkSpace\electron\EvPlayer\node_modules\electron-vite\dist\chunks\lib-86d699de.js:392:15)
    at createServer (D:\WorkSpace\electron\EvPlayer\node_modules\electron-vite\dist\chunks\lib-416c6508.js:52:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    at async CAC.<anonymous> (D:\WorkSpace\electron\EvPlayer\node_modules\electron-vite\dist\cli.js:43:9)

**Comment by alex8088** [comment]
The reason: `Error: Electron uninstall`, you need to npm install

**Comment by wcc1433** [comment]
PS D:\WorkSpace\electron\EvPlayer> npm install 

> evplayer@1.0.0 postinstall
> electron-builder install-app-deps

  • electron-builder  version=22.14.13
  • loaded configuration  file=D:\WorkSpace\electron\EvPlayer\electron-builder.yml

up to date in 2s

61 packages are looking for funding
  run `npm fund` for details
PS D:\WorkSpace\electron\EvPlayer> npm run dev

> evplayer@1.0.0 dev
> electron-vite dev

vite v2.9.5 building for development...
✓ 7 modules transformed.
out/main/index.js   8.61 KiB / gzip: 2.92 KiB

build the electron main process successfully

-----

vite v2.9.5 building for development...
✓ 1 modules transformed.
out/preload/index.js   0.41 KiB / gzip: 0.23 KiB

build the electron preload files successfully

-----

dev server running for the electron renderer process at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose
error during start dev server and electron app:
Error: Electron uninstall
    at Object.getElectronPath (D:\WorkSpace\electron\EvPlayer\node_modules\electron-vite\dist\chunks\lib-86d699de.js:392:15)
    at createServer (D:\WorkSpace\electron\EvPlayer\node_modules\electron-vite\dist\chunks\lib-416c6508.js:52:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    at async CAC.<anonymous> (D:\WorkSpace\electron\EvPlayer\node_modules\electron-vite\dist\cli.js:43:9)

**Comment by wcc1433** [comment]
已经 install了，还是这个错误

**Comment by alex8088** [comment]
检查  `node_modules\electron\dist` 和 `node_modules\electron\path.txt` 是否存在

**Comment by alex8088** [comment]
或者删除  node_modules 和 package-lock.json 重新安装
